# Generated by Django 4.2.8 on 2026-01-14 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='decisions/attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DecisionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pros', models.TextField(blank=True)),
                ('cons', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_time', models.CharField(blank=True, max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('default_title_pattern', models.CharField(help_text="e.g., 'Hire: {candidate_name}'", max_length=200)),
                ('default_description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public - Available to all teams'), ('private', 'Private - Only visible to creator'), ('team', 'Team - Visible to specific teams')], default='public', max_length=20)),
                ('is_system_template', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Template Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('currency', 'Currency'), ('date', 'Date'), ('select', 'Dropdown'), ('multiselect', 'Multiple Choice'), ('checkbox', 'Checkbox'), ('url', 'URL'), ('email', 'Email')], max_length=20)),
                ('help_text', models.TextField(blank=True)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('section', models.CharField(blank=True, help_text='Group fields into sections', max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='decisions.decisiontemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Review',
            new_name='DecisionReview',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='decisionversion',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='decisionversion',
            name='decision',
        ),
        migrations.AlterModelOptions(
            name='decisionreview',
            options={},
        ),
        migrations.RenameField(
            model_name='decision',
            old_name='decision_date',
            new_name='decided_at',
        ),
        migrations.AlterUniqueTogether(
            name='decisionreview',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='decision',
            name='implemented_date',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='version',
        ),
        migrations.AddField(
            model_name='decision',
            name='impact_score',
            field=models.IntegerField(default=0, help_text='Expected impact (0-100)'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AlterField(
            model_name='decision',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='decisions.team'),
        ),
        migrations.DeleteModel(
            name='AIAnalysis',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='DecisionVersion',
        ),
        migrations.AddField(
            model_name='templatefieldvalue',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_values', to='decisions.decision'),
        ),
        migrations.AddField(
            model_name='templatefieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decisions.templatefield'),
        ),
        migrations.AddField(
            model_name='decisiontemplate',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='decisions.templatecategory'),
        ),
        migrations.AddField(
            model_name='decisiontemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='decisions.decision'),
        ),
        migrations.AddField(
            model_name='decisionaudit',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='decisions.decision'),
        ),
        migrations.AddField(
            model_name='decisionaudit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionattachment',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='decisions.decision'),
        ),
        migrations.AddField(
            model_name='decisionattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decision',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='decisions.decisiontemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='templatefieldvalue',
            unique_together={('decision', 'field')},
        ),
    ]
